### ISSUE TITLE
color support

### ISSUE THREAD

**Issue by jorenham** [jorenham/numpy_turtle#4]
The currently only is support grayscale coloring.
If there are more than three array dimensions, assume the third to be the color channels.

**Comment by yingshaoxo** [comment]
Color is very important for drawing, please!

If you can add this feature, then we will be able to use this tool directly with opencv or moviepy to handle videos.

**Comment by jorenham** [comment]
Solved in https://github.com/jorenham/numpy_turtle/releases/tag/0.2
